# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Projects',           url: 'mainpage'}
- {name: 'Skills',             url: 'skills'}
# - {name: 'Sample Posts',       url: 'sample-posts'}
# - {name: 'Documentation',      url: 'documentation'}
- {name: 'About',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link:    'https://twitter.com/paululele'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
# - {icon: 'instagram', link:  'https://instagram.com/paululele'}
# - {icon: 'envelope', link:   'mailto:hello@paulle.ca'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/whitmanhall/'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Previous'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Posted on'
